### ISSUE TITLE
Overlay stays open and does not auto-minimize when a native game is launched

### ISSUE THREAD

**Issue by nyghtstalker** [HyperPlay-Gaming/hyperplay-desktop-client#537] opened 2023-09-19 18:20 UTC
### Describe the bug

When launching a native game the overlay normally opens for X amount of time and then auto-minimizes. The overlay now stays enabled until the user manually closes it.

### Add logs

```
(17:14:50) INFO:    [Legendary]:        Refreshing library...
(17:14:50) INFO:    [Legendary]:        Refreshing Epic Games...
(17:14:50) INFO:    [Backend]:          Loading MetaMask extension
(17:14:50) INFO:    [Connection]:       Connectivity: check-online
(17:14:50) INFO:    [Connection]:       Pinging external endpoints
(17:14:50) INFO:    [Backend]:          Creating abort controller for legendary-version
(17:14:51) INFO:    [Legendary]:        Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary --version
(17:14:51) INFO:    [Legendary]:        Legendary location: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary
(17:14:51) INFO:    [Gog]:              GOGDL location: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl
(17:14:51) INFO:    [Gog]:              GOGDL location: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl
(17:14:51) INFO:    [Legendary]:        Game list updated, got 358 games & DLCs
(17:14:51) WARNING: [Backend]:          Protocol already registered.
(17:14:51) INFO:    [Backend]:          App is starting in headless mode = undefined isCLINoGui = false startInTray = undefined
(17:14:51) INFO:    [Backend]:          MetaMask extension loaded
(17:14:51) INFO:    [Legendary]:        installed.json updated, refreshing library
(17:14:51) INFO:    [Backend]:          Creating abort controller for legendary-refresh
(17:14:51) INFO:    [Legendary]:        Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(17:14:51) INFO:    [Connection]:       Connectivity: online
(17:14:52) INFO:    [Backend]:          Auto Updater found version: 0.6.0 released on 2023-09-01T22:35:51.582Z with name 0.6.0
(17:14:52) INFO:    [Backend]:          Deleting abort controller for legendary-version
(17:14:52) INFO:    [Backend]:          Creating abort controller for gogdl-version
(17:14:52) INFO:    [Gog]:              Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --version
(17:14:52) INFO:    [Backend]:          Loading Screen Ready
(17:14:52) INFO:    [Frontend]:         Refreshing Library
(17:14:52) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(17:14:52) INFO:    [Legendary]:        Refreshing library...
(17:14:52) INFO:    [Legendary]:        Refreshing Epic Games...
(17:14:53) INFO:    [Legendary]:        Game list updated, got 358 games & DLCs
(17:14:53) INFO:    [Backend]:          Frontend Ready
(17:14:53) INFO:    [Backend]:          Creating abort controller for legendary-refresh
(17:14:53) INFO:    [Legendary]:        Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(17:14:53) INFO:    [WineDownloader]:   Updating wine versions info
(17:14:53) INFO:    [WineDownloader]:   Fetching upstream information...
(17:14:54) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(17:14:55) INFO:    [WineDownloader]:   wine versions updated
(17:14:55) ERROR:   [Backend]:          Could not find default wine version
(17:14:55) INFO:    [Backend]:          Deleting abort controller for legendary-refresh
(17:14:57) INFO:    [Backend]:          Deleting abort controller for legendary-refresh
(17:14:57) INFO:    [Backend]:          Creating abort controller for legendary-version
(17:14:57) INFO:    [Legendary]:        Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary --version
(17:14:57) INFO:    [Backend]:          Creating abort controller for gogdl-version
(17:14:57) INFO:    [Gog]:              Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --version
(17:14:57) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(17:14:57) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(17:14:58) INFO:    [Backend]:          Starting the Download Queue
(17:14:58) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(17:14:58) INFO:    [Backend]:          Deleting abort controller for legendary-version
(17:14:58) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d
(17:14:58) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d
(17:14:58) INFO:    [Legendary]:        Abort command "C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(17:14:58) INFO:    [Backend]:          Deleting abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(17:14:58) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(17:14:58) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(17:15:00) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d
(17:15:00) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d
(17:15:00) INFO:    [Legendary]:        Abort command "C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(17:15:00) INFO:    [Backend]:          Deleting abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(17:15:02) INFO:    [Backend]:          

HyperPlay Version: 0.6.0
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.6
OS: Microsoft Windows 10 Education KERNEL: 10.0.19045 ARCH: x64
CPU: Intel Core™ i7-6700K @4 
RAM: Total: 63.96 GiB Available: 37.18 GiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 2060 VRAM: 12288MB DRIVER: 536.99 


(14:28:34) INFO:    [ProtocolHandler]:  received 'hyperplay://launch/hyperplay/63f59264069b92b74c844c0b'
(14:28:34) INFO:    [HyperPlay]:        Game 63f59264069b92b74c844c0b not found in library. Adding it...
(08:41:08) INFO:    [Connection]:       Connectivity: offline
(08:41:09) INFO:    [Connection]:       Connectivity: check-online
(08:41:09) INFO:    [Connection]:       Pinging external endpoints
(08:41:09) INFO:    [Connection]:       Connectivity: online
(09:36:57) INFO:    [ProtocolHandler]:  received 'hyperplay://launch/hyperplay/63f59264069b92b74c844c0b'
(09:36:57) INFO:    [HyperPlay]:        Game 63f59264069b92b74c844c0b not found in library. Adding it...
(11:18:00) INFO:    [Backend]:          Creating abort controller for legendary-version
(11:18:00) INFO:    [Legendary]:        Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary --version
(11:18:01) INFO:    [Backend]:          Creating abort controller for gogdl-version
(11:18:01) INFO:    [Gog]:              Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --version
(11:18:02) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(11:18:02) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(11:18:02) INFO:    [Backend]:          Deleting abort controller for legendary-version
(11:18:04) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(11:18:04) INFO:    [Legendary]:        installed.json updated, refreshing library
(11:18:05) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d
(11:18:05) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d
(11:18:05) INFO:    [Legendary]:        Abort command "C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(11:18:05) INFO:    [Backend]:          Deleting abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(11:18:10) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for Another World
(11:18:11) INFO:    [HyperPlay]:        Getting install info for Another World
(11:18:11) INFO:    [HyperPlay]:        Getting install info for Another World
(11:18:11) INFO:    [HyperPlay]:        Getting install info for Another World
(11:18:11) INFO:    [HyperPlay]:        Getting install info for Another World
(11:18:14) INFO:    [Backend]:          Launching Another World (0xf00f316938650ff593911d28407672135546b08e4be3933ca7740ab0e6d12057)
(11:18:14) INFO:    [Backend]:          Preventing display from sleep
(11:18:14) INFO:    [HyperPlay]:        Getting install info for Another World
(11:18:14) INFO:    [HyperPlay]:        Getting install info for Another World
(11:18:15) INFO:    [Backend]:          launching native sideloaded or hyperplay store game: C:\Users\Joe\Games\HyperPlay\anotherworld\anotherworld\AnotherWorld.exe 
(11:18:15) INFO:    [Backend]:          Creating abort controller for 0xf00f316938650ff593911d28407672135546b08e4be3933ca7740ab0e6d12057
(11:18:15) INFO:    [Backend]:          Backend: LD_PRELOAD= C:\Users\Joe\Games\HyperPlay\anotherworld\anotherworld\C:\Users\Joe\Games\HyperPlay\anotherworld\anotherworld\AnotherWorld.exe
(11:18:15) DEBUG:   [Backend]:          Logging to file "C:\Users\Joe\AppData\Roaming\hyperplay\GamesConfig\0xf00f316938650ff593911d28407672135546b08e4be3933ca7740ab0e6d12057-lastPlay.log"
(11:18:15) INFO:    [Backend]:          overlay is shown ignoring mouse events:  {
  "overlayIsShown": true
}
(11:18:16) INFO:    [Frontend]:         Refreshing Library
(11:18:16) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(11:18:16) INFO:    [Legendary]:        Refreshing library...
(11:18:16) INFO:    [Legendary]:        Refreshing Epic Games...
(11:18:17) INFO:    [Legendary]:        Game list updated, got 358 games & DLCs
(11:18:17) INFO:    [Backend]:          Creating abort controller for legendary-refresh
(11:18:17) INFO:    [Legendary]:        Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(11:18:25) INFO:    [Backend]:          Deleting abort controller for legendary-refresh
(11:18:45) INFO:    [Backend]:          Aborting 0xf00f316938650ff593911d28407672135546b08e4be3933ca7740ab0e6d12057
(11:18:45) INFO:    [Backend]:          Aborted 0xf00f316938650ff593911d28407672135546b08e4be3933ca7740ab0e6d12057
(11:18:45) INFO:    [Backend]:          Trying to kill C:\Users\Joe\Games\HyperPlay\anotherworld\anotherworld\AnotherWorld.exe
(11:18:46) INFO:    [Backend]:          Killed C:\Users\Joe\Games\HyperPlay\anotherworld\anotherworld\AnotherWorld.exe
(11:18:46) INFO:    [Backend]:          Abort command "LD_PRELOAD= C:\Users\Joe\Games\HyperPlay\anotherworld\anotherworld\C:\Users\Joe\Games\HyperPlay\anotherworld\anotherworld\AnotherWorld.exe"
(11:18:46) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(11:18:46) INFO:    [Frontend]:         Refreshing Library
(11:18:46) INFO:    [HyperPlay]:        Getting install info for Another World
(11:18:46) INFO:    [HyperPlay]:        Getting install info for Another World
(11:18:47) INFO:    [HyperPlay]:        Getting install info for Another World
(11:18:47) INFO:    [HyperPlay]:        Getting install info for Another World
(11:18:52) INFO:    [Backend]:          operation interrupted
(11:18:59) INFO:    [Backend]:          Creating abort controller for legendary-version
(11:18:59) INFO:    [Legendary]:        Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary --version
(11:18:59) INFO:    [Backend]:          Creating abort controller for gogdl-version
(11:18:59) INFO:    [Gog]:              Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --version
(11:18:59) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(11:18:59) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(11:19:00) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(11:19:00) INFO:    [Backend]:          Deleting abort controller for legendary-version
(11:19:00) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d
(11:19:00) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d
(11:19:00) INFO:    [Legendary]:        Abort command "C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(11:19:00) INFO:    [Backend]:          Deleting abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(11:19:00) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(11:19:00) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(11:19:02) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d
(11:19:02) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d
(11:19:02) INFO:    [Legendary]:        Abort command "C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(11:19:02) INFO:    [Backend]:          Deleting abort controller for 98bc04bc842e4906993fd6d6644ffb8d
```

### Steps to reproduce

1. Launch a native game
2. Observe the overlay is opened shortly after the game is launched
3. Observe that the overlay does not auto-minimize

### Expected behavior

The overlay should auto-minimize after a set time

### Screenshots

![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/82125535/e530dfdd-f436-425e-abe9-3cf582153ed0)

### hyperplay Version

Latest Stable

### System Information

- Windows 10
- hyperplay Version 0.6.0

**Comment by awantoch** [comment] 2023-09-19 23:26
Decreasing priority now that we're:

1. Adding instructions on the overlay for how to toggle in #538 -- this will help with confusion drastically
2. Solving for the initial passthru issue where the overlay does not intercept input during initial launch in #541

**Comment by BrettCleary** [comment] 2023-09-27 04:11
the overlay is supposed to show if a notification is pending. in this case, another world is requesting your address but you have not logged into metamask. So it shows the overlay prompting you to unlock your MM wallet. This looks like the expected behavior to me

**Comment by awantoch** [comment] 2023-10-19 19:37
Closing as this is expected behavior when the wallet is locked

**Closed by awantoch** 2023-10-19 19:37 UTC
Labels: Type: Bug, Severity: 2 - Medium
