### ISSUE TITLE
Overlay should trigger without hotkey if requested by game

### ISSUE THREAD

**Issue by jacobc-eth** [HyperPlay-Gaming/hyperplay-desktop-client#173] opened 2023-03-07 21:26 UTC
Lots of players are missing overlay notifications because they odn't realize the need to manually trigger it. If an overlay notification or metamask confirmation is requested by a game, we should show it regardless of hotkey status.

**Comment by BrettCleary** [comment] 2023-04-05 01:43
duplicate of #237

**Closed by BrettCleary** 2023-04-05 01:43 UTC
