### ISSUE TITLE
Debug MetaMask mobile connection error using iOS

### ISSUE THREAD

**Issue by eliobricenov** [HyperPlay-Gaming/hyperplay-desktop-client#731] opened 2024-02-21 16:45 UTC
![Image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/38574891/f823663f-1c90-4782-80cf-11247b878e02)

**Comment by eliobricenov** [comment] 2024-02-21 17:17
I haven't been able to reproduce this. I will check later if we can get some reproduction steps.

**Comment by awantoch** [comment] 2024-02-21 22:38
This may solve it: https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/pull/739

**Comment by awantoch** [comment] 2024-02-27 20:06
Reopening as updating the SDK did not work

**Comment by awantoch** [comment] 2024-03-07 21:27
This may have to do with the .sdk file that can conflict when opening/closing the app quickly. TBD on exact issue and fix

**Comment by awantoch** [comment] 2024-03-07 21:28
Potential issue when using VPN on desktop but not on mobile (but VPN on mobile may also break)

**Comment by nyghtstalker** [comment] 2024-07-11 21:32
Unable to reproduce. Reopen at a later date if needed. Closing for now.

**Closed by nyghtstalker** 2024-07-11 21:32 UTC
Labels: Type: Bug, Severity: 1 - High
